spring.application.name=budgeting
# Chave de API gerada no Google AI Studio
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}

# Modelo do Gemini
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# Define a temperatura para 0.0 (equivalente no Whisper)
# Isso garante que a transcrição seja a mais determinística e exata possível
spring.ai.google.genai.chat.options.temperature=0.0

# Chave de API do ElevenLabs
spring.ai.model.audio.transcription=elevenlabs
spring.ai.elevenlabs.api-key=${ELEVENLABS_API_KEY}

# LOG mais detalhado
logging.level.org.springframework.ai=DEBUG

# Configurações do db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
